### ISSUE TITLE
Add Extensions for Codable

### ISSUE THREAD

**Issue by Mordil** [vapor/redis-kit#15]
RedisNIO doesn't have a Codable API, but Vapor's Redis module @ 3.x does.

We'll want to migrate / re-add those APIs to this module before V4 ships.

**Comment by JaapWijnen** [comment]
@Mordil I wanted to pick this up, but I'm not sure what Codable API you're mentioning. The only mention of Codable I can find is on the RedisClientConfig type. If you point me in the right direction I can try and make a PR :)

**Comment by Mordil** [comment]
@JaapWijnen [`jsonSet`](https://github.com/vapor/redis/blob/support-3/Sources/Redis/Client/Commands/Redis%2BBasic.swift#L109) and [`jsonGet`](https://github.com/vapor/redis/blob/support-3/Sources/Redis/Client/Commands/Redis%2BBasic.swift#L100)

**Comment by JaapWijnen** [comment]
@Mordil Thanks :), that also means implementing something similar to [`RedisDataConvertible`](https://github.com/vapor/redis/blob/b6c0c98d2219f550ccf23c4bb8f8b14d75356bc6/Sources/Redis/Data/RedisDataConvertible.swift#L4) right? EDIT: nvm I found RediStack already implements something similar :)

**Comment by tanner0101** [comment]
Fixed in #19
