### ISSUE TITLE
Support for Redis clusters

### ISSUE THREAD

**Issue by yuriferretti** [vapor/redis-kit#27]
I have a Redis cluster on AWS elasticache and using `request.redis.get` in order to retrieve cached data results on `MOVED <IP address>` errors which are the way Redis tell its clients should ask other node about this key.
Does this client implementation supports Redis clusters, is it in the future directions?

**Comment by Mordil** [comment]
@yuriferretti The client currently does not support Redis Clusters.

Please file an issue against [RediStack](https://gitlab.com/mordil/swift-redi-stack/issues)
